### ISSUE TITLE
where can "Download models and weights from the links given in TFJS Model URL"

### ISSUE THREAD

**Issue by ggzzzzz628** [ajaichemmanam/posenetv2-pythontf#2]
where can "Download models and weights from the links given in TFJS Model URL"

**Comment by ajaichemmanam** [comment]
I meant this file [TFJS Model URL](https://github.com/ajaichemmanam/posenetv2-pythontf/blob/master/TFJS%20Model%20URL) in repo

**Comment by ajaichemmanam** [comment]
Updated the readme.
